inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  Exclude:
    - 'db/**/*'
    - 'script/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    
  NewCops: enable

Layout/LineLength:
  Max: 150
  Exclude:
  - config/**/*

Metrics/BlockLength:
  Exclude:
    - config/**/*
    - spec/**/*

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Style/Documentation:
  Enabled: false